#server:
#  port: 8080
#
#spring:
#  rabbitmq:
#    host: ${application.spring.rabbitmq.host}
#    port: ${application.spring.rabbitmq.port}
#    username: ${application.spring.rabbitmq.username}
#    password: ${application.spring.rabbitmq.password}